version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./numbers.txt:/app/numbers.txt
      - ./log.json:/app/log.json
    ports:
      - "8080:8080"
